version: "3"
services:
  recorder:
    build: .
    volumes:
      - ./config:/usr/src/app/config
      - ./log:/usr/src/app/log
      - ./data:/usr/src/app/data
      - ./resolv.conf:/etc/resolv.conf
    restart: always
